In [1]:
import numpy as np
import pandas as pd

In [2]:
t_m_tr = pd.read_csv("t_m_tr.csv")

In [3]:
db_a = t_m_tr.sort_values(by = " count_sum")

db_1 = db_a[db_a["count_sum"]==1]
db_n1 = db_a[db_a["count_sum"]==1].index.values
db_not1 = db_a.drop(db_n1,axis = 0)

,Unnamed: 0,msno,payment_plan_days_mean,plan_list_price_mean,plan_list_price_sum,count_sum,city,bd,gender,registered_via,registration_init_time,index,is_churn
0,0,+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,30.000000,99.000000,198.0,2.0,1,0,NaN,7,20140608,0,0.0
1,1,+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=,15.000000,74.500000,298.0,2.0,15,26,male,9,20101118,1,0.0
2,2,+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=,15.000000,74.500000,149.0,1.0,1,0,NaN,7,20140927,2,0.0
3,3,++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=,30.000000,149.000000,298.0,2.0,18,21,male,7,20160315,3,0.0
4,4,++/UDNo9DLrxT8QVGiDi1OnWfczAdEwThaVyD0fXO50=,15.000000,74.500000,149.0,1.0,22,32,male,9,20120122,4,0.0
5,5,++/ZHqwUNa7U21Qz+zqteiXlZapxey86l6eEorrak/g=,30.000000,149.000000,447.0,3.0,13,39,male,3,20140421,5,0.0
6,6,++0/NopttBsaAn6qHZA2AWWrDg7Me7UOMs1vsyo4tSI=,30.000000,149.000000,298.0,2.0,1,0,NaN,7,20160320,6,0.0
7,7,++0nOC7BmrUTtcSboRORfg6ZXTajnBDt1f/SEgH6ONo=,15.000000,74.500000,149.0,1.0,13,25,male,9,20100203,9,0.0
8,8,++1G0wVY14Lp0VXak1ymLhPUdXPSFJVBnjWwzGxBKJs=,30.000000,99.000000,198.0,2.0,1,0,NaN,7,20150909,11,0.0
9,9,++1GCIyXZO7834NjDKmcK1lBVLQi9PsN6sOC7wfW+8g=,15.000000,49.500000,99.0,1.0,1,0,NaN,7,20160705,12,0.0
10,10,++38dVm0EHKCOfND6oEal3xFKtqJYZTZJmnpbAOOZBk=,15.000000,49.500000,99.0,1.0,1,0,NaN,7,20151023,15,0.0
11,11,++3A6JMzYJeron30GTcDostfXoAl8rTBuB2M8GeVdNU=,15.000000,74.500000,149.0,1.0,1,0,NaN,7,20150312,16,0.0
12,12,++3Z+W8OPnpbHYfrKwqRKN1bF83XEbxjdYUolhGdHZg=,30.000000,142.333333,556.0,4.0,5,35,female,7,20120209,17,0.0
13,13,++3fWHRDC5GWWlovHcrOKWNwZYOjWWkJyeLlL65uv78=,30.000000,99.000000,198.0,2.0,1,0,NaN,7,20160121,18,0.0
14,14,++3wqX72HmowxFh5MrHvNi5Ce8D3ldo4zaUL932TYbs=,30.000000,99.000000,297.0,3.0,1,0,NaN,7,20131016,19,0.0
15,15,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,30.000000,149.000000,298.0,2.0,1,0,NaN,7,20140714,20,0.0
16,16,++4cUL0b9CfW8cj0A/wfSxQc4k4fcVtWcLqk2UOdpKs=,15.000000,74.500000,149.0,1.0,15,28,male,7,20121009,21,0.0
17,17,++5BmBHS2ebe4Whfg/7KhGkj/sQ6rtNHsktLxsI01KE=,30.000000,149.000000,298.0,2.0,6,0,NaN,3,20130305,24,0.0
18,18,++5wYjoMgQHoRuD3GbbvmphZbBBwymzv5Q4l8sywtuU=,30.166667,149.000000,745.0,5.0,13,39,male,9,20060218,28,0.0
19,19,++6P09mCSJSh+Ft2pvZ0FWTrtcI3v1A7h3/coh8dBKw=,30.000000,149.000000,298.0,2.0,22,35,male,9,20100921,30,0.0
20,20,++6xEqu4JANaRY4GjEfEFtLtqOvZvYPyP3uk/PW9Ces=,30.000000,99.000000,198.0,2.0,1,0,NaN,7,20160501,31,0.0
21,21,++7IULiyKbNc8jllqhRuyKZjX1J4mPF4tsudFCJfv4k=,15.000000,74.500000,149.0,1.0,5,38,female,9,20100127,33,0.0
22,22,++8dXbkKMJ0rXwUc/m19lTVokEl3c9EfRKWmV6qP9jg=,15.000000,49.500000,99.0,1.0,1,0,NaN,7,20160321,35,0.0
23,23,++95tJZADNg8U8HKbYdxbbXIRsO6pw1zBK4tHI7BtZo=,30.000000,149.000000,298.0,2.0,14,35,female,3,20120603,36,0.0
24,24,++A8p4GrsTnMjI6hAZEtlRsaz6s6O9ddUoH0fmS4s7s=,15.000000,74.500000,149.0,1.0,5,43,female,9,20141118,38,0.0
25,25,++BBU1qnsavj2eC5j5G6dTda9ntLhRiz+pidG73im5s=,15.000000,74.500000,298.0,2.0,17,26,female,9,20090917,39,0.0
26,26,++BQyzVEMoHru900mTyAKpCsKYjXUGdAXylmmiPsbVY=,15.000000,74.500000,149.0,1.0,1,0,NaN,7,20151228,40,0.0
27,27,++BW1PJYU5OZi3n3+IDLiU+d1IL1VE/GLx6p64TDs6U=,15.000000,74.500000,298.0,2.0,15,29,male,9,20070609,41,0.0
28,28,++Ck01c3EF07Ejek2jfXlKut+sEfg+0ry+A5uWeL9vY=,30.000000,99.000000,198.0,2.0,1,0,NaN,7,20131229,45,0.0
29,29,++CzVs35NSfU/gjDrGbWLVMweubEiMZsuvd3eTbXs58=,30.000000,124.000000,248.0,2.0,1,0,NaN,7,20150914,46,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
766472,766472,zznuqn+KaqC3TAIy7ulqyWKSGy7Mzsg5Br2Li0Wgd4Y=,15.000000,74.500000,149.0,1.0,1,0,NaN,7,20140427,1036160,0.0
766473,766473,zznxIK74CmFA4ctJV0OdqizliOysqwVH3HYqSRatwjQ=,30.000000,139.000000,278.0,2.0,1,25,female,7,20120710,1036161,0.0
766474,766474,zzoDlpMVa28r4EW18mzyEFDu/c/swxxeMPGLTinccc4=,195.500000,674.500000,1349.0,2.0,22,19,male,9,20130917,1036162,1.0
766475,766475,zzompfSaMamqvjyCMYvgUBwYrxh8fHE40z3f73CQoak=,15.000000,74.500000,149.0,1.0,12,25,male,3,20130221,1036163,0.0
766476,766476,zzp++cVQOL+vApgAvHD7JtTt69oNArzMt0gWhVY7e1w=,15.000000,74.500000,298.0,2.0,1,0,NaN,7,20140311,1036164,0.0
766477,766477,zzpF6hy2lJv8GjT/eZOGSCmg/kQ5FtuIuI+EUaAx7YU=,30.000000,149.000000,298.0,2.0,1,0,NaN,7,20130123,1036165,0.0
766478,766478,zzpTXKXmUXusfh8lgKDrPLEdQyNOvxl4a+PE0CwQIQU=,30.000000,124.000000,546.0,4.0,1,0,NaN,7,20131210,1036166,0.0
766479,766479,zzqhrI0gqPwQnjjWX4PC16TgaLSUwQaejWWeJjclfW8=,15.000000,74.500000,149.0,1.0,1,0,NaN,7,20130609,1036168,0.0
766480,766480,zzqv/DjiJJFlfDEeaja2Cq7cvVWz++pwIaJ6SAM42sw=,30.000000,144.000000,427.0,3.0,1,0,NaN,7,20131227,1036169,0.0
766481,766481,zzsumtyPQEJN7XNakERtaZiXsGmc786aWSHFScPfV5k=,15.000000,74.500000,149.0,1.0,1,39,male,4,20170115,1036172,1.0
766482,766482,zzsusjoGJ6jH+qVF5cMfJGphBO7MR4P4P1rD7qxITX0=,30.000000,149.000000,298.0,2.0,4,27,female,9,20120923,1036173,0.0
766483,766483,zzt4LinfZVgufjQc8MVgTz9CwxB9pJtNJDnk3d3F7Ac=,15.000000,74.500000,149.0,1.0,13,20,male,9,20110318,1036174,0.0
766484,766484,zztGcSZznx0uMBvc0fTQVTfCzeS7Ho/otO2L/4FXs/w=,15.000000,74.500000,149.0,1.0,3,29,male,9,20070605,1036175,0.0
766485,766485,zztb7cCNxnkeZ33rHQ0Z3cnshdE8gn/nwMTiNP49b4o=,15.000000,74.500000,298.0,2.0,15,26,male,9,20100211,1036177,0.0
766486,766486,zzuGxQfF86Zsx5nqF1Yh+oJpEIfdjFKKYpTqFZMdxzk=,30.500000,149.000000,298.0,2.0,22,30,male,9,20051216,1036178,0.0
766487,766487,zzv/igs0VigNppe7WR8qgz1h6aXFFzQLu5paAswIbcQ=,15.000000,74.500000,298.0,2.0,14,33,male,9,20060721,1036180,0.0
766488,766488,zzv2n8+r3LGI4gFp6c4hpseYdfHrl829IY3IlA0BF4Q=,15.000000,74.500000,149.0,1.0,13,0,NaN,7,20130412,1036181,0.0
766489,766489,zzvB5JRK4WBwtKJoNtnNF34r5dUAuenPpR9xrxdfMSI=,15.000000,49.500000,99.0,1.0,1,0,NaN,7,20130805,1036182,0.0
766490,766490,zzvRDIlZcYclP7ocM+wG1WUPbUHPtMRPKerl/hionLg=,15.000000,64.500000,129.0,1.0,1,0,NaN,7,20170210,1036183,0.0
766491,766491,zzvhQSh5Xs6/9DO+wUTtEbSZRBHjGIpHMOP2kVMrXmk=,30.000000,99.000000,198.0,2.0,1,0,NaN,7,20160202,1036185,0.0
766492,766492,zzwimfmJBJ4SrRw3bYXQzE9UrizlSE10yI7dHPvG5xM=,30.000000,99.000000,198.0,2.0,18,43,female,7,20161020,1036186,0.0
766493,766493,zzwlIVmSuehTevzOi+WkcC7b3+MBYDiE4qybszTyhII=,15.000000,74.500000,149.0,1.0,13,26,male,4,20160416,1036187,0.0
766494,766494,zzwsW1MnZalh6V5BwYE+V6hFWyKJYOf+rFd+SWVXxp8=,30.000000,99.000000,297.0,3.0,1,0,NaN,7,20151006,1036188,0.0
766495,766495,zzx1qgX8R9EmT8PAn4/KyQ6s7PuLYTfR8kUCABiCW9E=,15.000000,49.500000,99.0,1.0,6,31,male,9,20141014,1036189,0.0
766496,766496,zzx4hKiyR9XFEGAr7SAjcCPbKJCZ+IqegWL7dPjPwZk=,30.000000,124.000000,546.0,4.0,1,0,NaN,7,20110823,1036190,0.0
766497,766497,zzxPS8+wCuE4HE85EDp4WBHgS5l548vfwXJbQq1HZ9I=,30.000000,149.000000,298.0,2.0,22,28,female,9,20070810,1036192,0.0
766498,766498,zzxZeMFx2fjfKZigMnJa2w0EmloDbm8+8nTf/o/00GY=,30.000000,107.333333,446.0,4.0,4,24,male,7,20120306,1036193,0.0
766499,766499,zzy7iqSpfcRq7R4hmKKuhI+CJRs79a6pteqEggpiNO0=,15.000000,90.000000,180.0,1.0,5,31,male,3,20150430,1036195,1.0
766500,766500,zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q=,15.000000,74.500000,149.0,1.0,4,48,female,9,20140611,1036196,0.0
766501,766501,zzzF1KsGfHH3qI6qiSNSXC35UXmVKMVFdxkp7xmDMc0=,15.000000,74.500000,149.0,1.0,4,26,male,3,20170129,1036198,0.0